### PR TITLE
Myelin

### PR DESCRIPTION
**Pull request by jingpengw**
- add setup-env operator to automatically prepare environment
- avoid mask buffer to make memory usage more efficient
- refactor normalize-section-contrast operator to make it faster and easier to use

### CODE REVIEW

**Comment by shangmu** [comment]
The whole Image class is broken. Master branch is supposed to be a useable branch.

**Comment by jingpengw** [comment]
hmm, will take look. thanks!

**Comment by jingpengw** [comment]
@shangmu could you try the `fix-image` branch?
https://github.com/seung-lab/chunkflow/pull/161

**Comment by jingpengw** [comment]
I have merge the branch to master to fix the travis tests.

**Comment by shangmu** [comment]
What I mean by the Image class being broken is it won't even get instantiated:
`class Image(Chunk):
    def __new__(cls, array, **kwargs):
        ...
        obj = Chunk(array, global_offset=global_offset, *kwargs).view(cls)`
There isn't even a `view()` method anymore.

**Comment by jingpengw** [comment]
I see. have fixed this and made some unit tests.
I will merge the fix soon.

Jingpeng Wu
Postdoc in Princeton Neuroscience Institute, Princeton University, NJ
website: jingpengw.com

**Pull request merged**
